defaults: &defaults
  aws_aki:         ABCDEFG
  aws_sak:         ABCDEFG
  aws_bucket:      ABCDEFG
  facebook_page:   http://www.facebook.com/pages/meals4me/149705428516213
  gmail_usr:       email@email.com
  gmail_pwd:       ABCDEFG
  interfax_url:    https://ws.interfax.net/dfs.asmx?WSDL
  interfax_usr:    ABCDEFG
  interfax_pwd:    ABCDEFG
  mfm_mode:        Test
  tropo_url:       https://api.tropo.com/1.0/sessions
  tropo_token:     ABCDEFG
  twitter_page:    https://twitter.com/MealsForMe

production:
  <<: *defaults

  domain: localhost

  paypal_email:    production@example.com
  paypal_secret:   production_secret
  paypal_cert_id:  production_cert_id
  paypal_base_url: https://www.paypal.com/cgi-bin/webscr

development:
  <<: *defaults

  domain: localhost

  paypal_email:    development@example.com
  paypal_secret:   development_secret
  paypal_cert_id:  development_cert_id
  paypal_base_url: https://www.sandbox.paypal.com/cgi-bin/webscr

test:
  <<: *defaults

  domain: localhost

  paypal_email:    test@example.com
  paypal_secret:   test_secret
  paypal_cert_id:  test_cert_id
  paypal_base_url: https://www.sandbox.paypal.com/cgi-bin/webscr
