defaults: &defaults
  main_email:      main_email@example.com
  main_password:   main_password
  aws_aki:         ABCDEFG
  aws_sak:         ABCDEFG
  aws_bucket:      ABCDEFG

production:
  <<: *defaults

  domain: localhost

  paypal_email:    production@example.com
  paypal_secret:   production_secret
  paypal_cert_id:  production_cert_id
  paypal_base_url: "https://www.paypal.com/cgi-bin/webscr"

development:
  <<: *defaults

  domain: localhost

  paypal_email:    development@example.com
  paypal_secret:   development_secret
  paypal_cert_id:  development_cert_id
  paypal_base_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  <<: *defaults

  domain: localhost

  paypal_email:    test@example.com
  paypal_secret:   test_secret
  paypal_cert_id:  test_cert_id
  paypal_base_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
