defaults: &defaults
  main_email:      main_email@example.com
  main_password:   main_password

development:
  <<: *defaults
  paypal_email:    development@example.com
  paypal_secret:   development_secret
  paypal_cert_id:  development_cert_id
  paypal_base_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  <<: *defaults
  paypal_email:    test@example.com
  paypal_secret:   test_secret
  paypal_cert_id:  test_cert_id
  paypal_base_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

production:
  <<: *defaults
  paypal_email:    production@example.com
  paypal_secret:   production_secret
  paypal_cert_id:  production_cert_id
  paypal_base_url: "https://www.paypal.com/cgi-bin/webscr"